### ISSUE TITLE
\\newline Command not working on swiftUI IOS

### ISSUE THREAD

**Issue by IngeniousMaths** [mgriebling/SwiftMath#1]
Hi, I've adopted the dependency on a side project I'm working on in SwiftUI for IOS, however I cant seem to create a new line or wrap the equation to be confined in frame or container with a specific width..

can you please help

**Comment by mgriebling** [comment]
SwiftMath only implements a subset of LaTeX associated with commands used within the math mode environment so \newline is not supported.  You can force line breaks using math mode commands (e.g., \\ as in \text{Quadratic roots: }x = \\ \frac{-b \pm \sqrt{b^2-4ac}}{2a} to give

<img width="318" alt="Screenshot 2023-02-23 at 8 00 59 AM" src="https://user-images.githubusercontent.com/2421348/220913664-bec1c330-51e1-4067-8fd3-37aa306ddd6f.png">
