### ISSUE TITLE
Swedish characters not rendering in \text{}

### ISSUE THREAD

**Issue by OskarPersson** [mgriebling/SwiftMath#14]
Rendering `\text{abc åäö def}` only displays "abc  def". Even when using the Latin Modern Math font which looks like it should include these characters according to https://www.cdnfonts.com/latin-modern-math.font

**Comment by petersktang** [comment]
characters dropped by the below.
``` swift
public static func atom(forCharacter ch: Character) -> MTMathAtom? {
        let chStr = String(ch)
        switch chStr {      
            case _ where ch.utf32Char < 0x0021 || ch.utf32Char > 0x007E:
                return nil
```

**Comment by mgriebling** [comment]
Accented text characters are not currently supported since this is primarily a math environment.
This was a limitation of the original source code (iosMath) as well.
TeX only supported accented text using \', \", etc. This is not currently supported in text mode.

**Comment by mgriebling** [comment]
Anyone is invited to add accent commands.  Note: This is likely a nontrivial addition.

**Comment by OskarPersson** [comment]
I got swedish characters working with the default font and the following change https://github.com/OskarPersson/SwiftMath/commit/8e18aab81e0f69d49a93d8caa2cae84cef98eeda

Could not get italics to work though (haven't really investigated why yet), but it shows åäö both inside and outside of `\text{}`

**Comment by mgriebling** [comment]
I would prefer to make this more generic to also support other European accents. The double-dot is already supported via the \ddot command. The Å is also supported already via the \angstrom command. Only the å support is missing.
What could be done is to auto-translate the Unicode characters to the internal accent commands to make things more convenient for accented languages. I'll see what's involved in doing this.
