### ISSUE TITLE
How can i use other fonts ?

### ISSUE THREAD

**Issue by nicohirtt** [mgriebling/SwiftMath#20]
SwiftMath is wonderfull. I'm trying to integrate it in my project EureKalc. But I don't understand how to manage using other fonts thant those provided. You writ : "you can use any OTF math font." But the mathFonts bundle contains, for each font, a .ort file and a .plist. I found some .otf files for math fonts on the web. But no .plist file. I suppose I did not understand something important. Can you help ???
Thanks !
Nico

**Comment by mgriebling** [comment]
Unfortunately adding new fonts is non-trivial.  You must first find a font that contains the math symbols required by SwiftMath.  Secondly, you need to generate the .plist file using the math_table_to_plist.py utility from iosMath.  Finally, you need to create a bundle file using Xcode that can be read by SwiftMath.

**Comment by nicohirtt** [comment]
Thanks a lot ! I’ll try that.

Nico Hirtt
8 rue du Sart
7180 Seneffe
Belgique

+32 474 29 52 54
+32 64 33 81 31

***@***.***
