### ISSUE TITLE
Inline Math / Combining Regular Text and Latex

### ISSUE THREAD

**Issue by swiftly-viper** [mgriebling/SwiftMath#23]
Hello,

Is there a way to combine both regular text and latex using SwiftMath? Mimicking functionality like "$...$" in MathJax, for example. The built-in labelMode, from what I can tell, does not do this. 

Thank you

**Comment by mgriebling** [comment]
Unfortunately this is not a simple addition. It requires an entirely new architecture where the existing math environment becomes part of a larger more LaTex-orientated library. Supporting LaTex is done already by others such as MathJax, etc so this is not something I would duplicate here.

**Comment by swiftly-viper** [comment]
Thank you for the reply,

Forgive me if I used the term "LaTeX" loosely, I believe the way I used it in the original message was incorrect. What I meant by "LaTeX" was the mathematical display produced by SwiftMath. Essentially, I am curious whether I could contain both regular text and math display in one view, essentially the inline mode supported by MathJax. Something like:

"The Pythagorean Theorem is $a^2 + b^2 = c^2$", where the normal text would appear as If I used Text("") and the string between $...$ would be stylized by SwiftMath.

Just wanted to clarify as I forgot to consider LaTeX and iOSMath/SwiftMath are different. 

Unrelated to the original question: Is there a way that you know of to bolden the latinmodern math font used by SwiftMath? Looking at iOSMath's code, it seems it is hinted that such an option exists somewhere. The thinness of the font has been particularly striking, so I've been trying to search for a solution.

Thank you for your reply!

**Comment by mgriebling** [comment]
Look at my SwiftMathDemo for examples of what you want.

Here's the quadratic equation:

"\\text{Quadratic roots: }x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}"

**Comment by swiftly-viper** [comment]
Thanks for the demo. It was a helpful resource. Based on what I've seen in the demo, and the examples you provided, I have come to the following conclusions:

1. Inline text is only possible with the "\text" command. Therefore, something like what I've tried below is impossible (changing the font attributes of the regular, non-mathematic, text).

MathView(equation: "\\text{Mary has }\\$500 + \\$200.")
     .font(.custom("DMSans-Regular", size: 30))
     
2. It is not possible to display using a bolder version of the LatinModern Math font without using commands such as "\mathbfit"

Would it be possible to confirm these two conclusions? I would appreciate it.

Thank you for your replies so far as well!

**Comment by mgriebling** [comment]
Each math view only has one font (chosen with the .font environment variable) and font variants selected within the view by the \\mathrm, \\mathbf,  \\mathcal,  \\mathfrak, \\mathsf, \\bm, \\mathtt, or \\mathit commands.  Any reason you can't use multiple views to accomplish what you want?

Since I'm not the original author of this package (check with [iosMath](https://github.com/kostub/iosMath)) for more in-depth implementation details.
