### ISSUE TITLE
Support for Custom Commands in Swift Math

### ISSUE THREAD

**Issue by swiftly-viper** [mgriebling/SwiftMath#25]
Hello,

SwiftMath's ReadME contains the following passage:

"Custom Commands
You can define your own commands that are not already predefined. This is similar to macros is LaTeX. To define your own command use:

MTMathAtomFactory.addLatexSymbol("lcm", value: MTMathAtomFactory.operator(withName: "lcm", limits: false))

This creates an \lcm command that can be used in the LaTeX."

It is different than that of iOSMath's ReadMe, suggesting it can be done in SwiftMath as well. I installed the package using Swift Package Manager and wanted to know how we can add custom commands without the ability to edit the source code directly.

For example, if I wanted to add the secant function for SwiftMath, what way would you suggest? Can the MathView struct be edited (as seen in the SwiftMathDemo you provided) to enhance its functionality?

I apologize if this is an elementary question. I have asked others but have been unsuccessful in finding an adequate solution.

Thank you!

**Comment by mgriebling** [comment]
Adding new commands requires source code changes.
