### ISSUE TITLE
Displaying Math Equations from ChatGPT responses.

### ISSUE THREAD

**Issue by tobitech** [mgriebling/SwiftMath#27]
Hello, I got a response from ChatGPT and tried to display it with SwiftMath but it didn't work:

Here is the response:
```
To solve the equation \(3x + 5 = 4\), follow these steps:
what format is this string of text:
1. Subtract 5 from both sides of the equation to isolate the term with \(x\):
   \[
   3x + 5 - 5 = 4 - 5
   \]
   Simplifying this, we get:
   \[
   3x = -1
   \]
2. Divide both sides by 3 to solve for \(x\):
   \[
   x = \frac{-1}{3}
   \]
So, the solution to the equation \(3x + 5 = 4\) is:
\[
x = -\frac{1}{3}
\]
```

When I tried with another package I get the error: Undefined control sequence `\(`
I don't know what I need to do to be able to display this type of response.

**Comment by mgriebling** [comment]
This is LaTeX output. SwiftMath only supports a subset of LaTeX, namely equations.

**Comment by tobitech** [comment]
@mgriebling Thank you for your response. Do you have any recommendations on how to display this type of LaText output in SwiftUI?

**Comment by mgriebling** [comment]
Maybe look at embedding [MathJax](https://www.mathjax.org) within a web browser view.
