### ISSUE TITLE
Chinese characters within text

### ISSUE THREAD

**Issue by leemckelvey** [mgriebling/SwiftMath#29]
I am trying to write a question in both English and Chinese, of the form:

Solve the equation ax+b=c
解方程 ax+b=c

My problem is that the Chinese characters do not show up at all when using MTMathUILabel.

A snippet of my code is below:

label.latex = "\\text{ Solve the equation}" + "ax+b=c" + "\\\\ 解方程 ax+b=c"

Any help on this would be very much appreciated as it shows nothing no matter what I try.

**Comment by mgriebling** [comment]
Chinese is not supported. Only European character sets and some Cyrillic.

**Comment by leemckelvey** [comment]
oh that's a shame, can I ask if you know if it ever worked for iOSMath? I am sure I found a blog with people suggesting it did.

Thank you for responding.

**Comment by mgriebling** [comment]
If you can provide more details on what font was used, I can look into it. But, AFAIK no Chinese character support was provided by iOSMath.

**Comment by leemckelvey** [comment]
I found the link again with the conversation about Chinese added.

https://github.com/kostub/iosMath/pull/29

I did try iOSMath and did also add the font mentioned but to no avail.

Thanks again

**Comment by mgriebling** [comment]
Looked into this and this was a temporary addition that was later removed. It's unclear why. Likely there was some issue or the original contributor decided not to publish his font. That's also why the current code doesn't support Chinese characters.

**Comment by leemckelvey** [comment]
Thank you so much for checking :) I really appreciate it.

Lee
