### ISSUE TITLE
Vertical alignment of text in MTMathUILabel

### ISSUE THREAD

**Issue by leemckelvey** [mgriebling/SwiftMath#30]
Is it possible to vertically align the text so that it always writes from the top left of a MTMathUILabel?

I know you can use "MTEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)" for fine tuning but I was hoping to force it to stay in the same position no matter how much text is put into the label.

Thanks

**Comment by mgriebling** [comment]
Do you have an example of what doesn't work?
Normally text should start at the top and left assuming you're using the

**Comment by leemckelvey** [comment]
If I use multiple lines for my label then it pushes the whole label upwards. I want questions with 1 or multiple lines of text.

<img width="665" alt="Screenshot 2024-10-06 at 16 02 26" src="https://github.com/user-attachments/assets/9956d2ed-3e9a-474d-85e0-f6c173cf0ff6">
 This is what it looks likes with one line of text.

<img width="665" alt="Screenshot 2024-10-06 at 16 01 36" src="https://github.com/user-attachments/assets/98ab27ad-f0f0-44f1-a706-a327900cd64b">
As you increase the number of lines of text (using "////" for new line) then the above happens.

I can fix this using MTEdgeInsets, but I would rather it is dynamic for me :)
<img width="842" alt="Screenshot 2024-10-06 at 16 05 05" src="https://github.com/user-attachments/assets/a0bafcec-b34c-4bca-8990-3cd1f9765430">

Thanks as always.

**Comment by mgriebling** [comment]
Here's the code I used (SwiftUI):

```swift
                MathView(equation: 
                         """
                         \\text{1. }
                         \\text{Solve the equation } 16x + 6 = -6x + 1\\\\
                         \\text{Solve the equation } 16x + 6 = -6x + 1\\\\
                         \\text{Solve the equation } 16x + 6 = -6x + 1
                        """)
```

and the result:

![Screenshot 2024-10-06 at 8 47 07 AM](https://github.com/user-attachments/assets/7d4e1bd0-fe64-4045-8c87-6ce7a0989727)

Not sure what you're using to make the red box or what your code looks like.  I assume you want the box
to stay around the "1."?  My edgeinsets are all at zero.

**Comment by leemckelvey** [comment]
I am using Mac OS to code this, the red box is literally just placed in a template that the MTMathUILabels get written onto. I put everything into view controllers and then it spits out a compiled pdf with all questions. But not to worry I can adjust the label position appropriately as the questions won't change other than randomly generated numbers. :)

**Comment by mgriebling** [comment]
BTW, here's how I would solve your problem using SwiftUI:

```swift
                HStack(alignment: .top) {
                    RoundedRectangle(cornerRadius: 10)
                        .fill(.blue)
                        .frame(width: 60, height: 40)
                        .overlay {
                            MathView(equation: "\\text{1.}")
                        }
                    MathView(equation:
                        """
                      \\text{Solve the equation } 16x + 6 = -6x + 1\\\\
                      \\text{Solve the equation } 16x + 6 = -6x + 1\\\\
                      \\text{Solve the equation } 16x + 6 = -6x + 1
                      """
                    )
                    .padding(.top, 10)
                }
```

This gives:
![Screenshot 2024-10-06 at 9 51 34 AM](https://github.com/user-attachments/assets/d06d83a9-33dd-4169-9506-0b7d5650cd55)

**Comment by leemckelvey** [comment]
Ooh padding, I will try this.

Thank you!
