### ISSUE TITLE
Impossible to display simple quote

### ISSUE THREAD

**Issue by AriOS-app** [mgriebling/SwiftMath#35]
Hi there,

Sometimes the api that I use gives me text in latex format and I use the following function to replace special characters. I tried many thing but impossible to get a single quote. Any solution?

```
extension String {
    func toLaTeX() -> String {
        let mappings: [Character: String] = [
            // Acute accents
            "á": #"\acute{a}"#, "é": #"\acute{e}"#, "í": #"\acute{i}"#, 
            "ó": #"\acute{o}"#, "ú": #"\acute{u}"#, "ý": #"\acute{y}"#,
            
            // Grave accents
            "à": #"\grave{a}"#, "è": #"\grave{e}"#, "ì": #"\grave{i}"#, 
            "ò": #"\grave{o}"#, "ù": #"\grave{u}"#,
            
            // Circumflex
            "â": #"\hat{a}"#, "ê": #"\hat{e}"#, "î": #"\hat{i}"#, 
            "ô": #"\hat{o}"#, "û": #"\hat{u}"#,
            
            // Umlaut/dieresis
            "ä": #"\ddot{a}"#, "ë": #"\ddot{e}"#, "ï": #"\ddot{i}"#, 
            "ö": #"\ddot{o}"#, "ü": #"\ddot{u}"#, "ÿ": #"\ddot{y}"#,
            
            // Tilde
            "ã": #"\tilde{a}"#, "ñ": #"\tilde{n}"#, "õ": #"\tilde{o}"#,
            
            // Special characters
            "ç": #"\c{c}"#,
            "ø": #"\o"#,
            "å": #"\aa"#,
            "æ": #"\ae"#,
            "œ": #"\oe"#,
            "ß": #"\ss"#,
            "'": #"\\textquotesingle"#, <----------- HERE
            
            // Upper case variants
            "Á": #"\acute{A}"#, "É": #"\acute{E}"#, "Í": #"\acute{I}"#,
            "Ó": #"\acute{O}"#, "Ú": #"\acute{U}"#, "Ý": #"\acute{Y}"#,
            "À": #"\grave{A}"#, "È": #"\grave{E}"#, "Ì": #"\grave{I}"#,
            "Ò": #"\grave{O}"#, "Ù": #"\grave{U}"#,
            "Â": #"\hat{A}"#, "Ê": #"\hat{E}"#, "Î": #"\hat{I}"#,
            "Ô": #"\hat{O}"#, "Û": #"\hat{U}"#,
            "Ä": #"\ddot{A}"#, "Ë": #"\ddot{E}"#, "Ï": #"\ddot{I}"#,
            "Ö": #"\ddot{O}"#, "Ü": #"\ddot{U}"#,
            "Ã": #"\tilde{A}"#, "Ñ": #"\tilde{N}"#, "Õ": #"\tilde{O}"#,
            "Ç": #"\c{C}"#,
            "Ø": #"\O"#,
            "Å": #"\AA"#,
            "Æ": #"\AE"#,
            "Œ": #"\OE"#
        ]
        
        return self.map { mappings[$0] ?? String($0) }.joined()
    }
}
```

**Comment by OskarPersson** [comment]
I see that you also have å in your list of special characters, does that work? If so, how do you use it?

**Comment by mgriebling** [comment]
You can produce a single back quote as: `.  Feel free to add the missing single quote ' command.
I don't believe a raised circle (e.g., å) is currently supported.

**Comment by mgriebling** [comment]
> Hi there,
> 
> Sometimes the api that I use gives me text in latex format and I use the following function to replace special characters. I tried many thing but impossible to get a single quote. Any solution?
> 
> ```
> extension String {
>     func toLaTeX() -> String {
>         let mappings: [Character: String] = [
>             // Acute accents
>             "á": #"\acute{a}"#, "é": #"\acute{e}"#, "í": #"\acute{i}"#, 
>             "ó": #"\acute{o}"#, "ú": #"\acute{u}"#, "ý": #"\acute{y}"#,
>             
>             // Grave accents
>             "à": #"\grave{a}"#, "è": #"\grave{e}"#, "ì": #"\grave{i}"#, 
>             "ò": #"\grave{o}"#, "ù": #"\grave{u}"#,
>             
>             // Circumflex
>             "â": #"\hat{a}"#, "ê": #"\hat{e}"#, "î": #"\hat{i}"#, 
>             "ô": #"\hat{o}"#, "û": #"\hat{u}"#,
>             
>             // Umlaut/dieresis
>             "ä": #"\ddot{a}"#, "ë": #"\ddot{e}"#, "ï": #"\ddot{i}"#, 
>             "ö": #"\ddot{o}"#, "ü": #"\ddot{u}"#, "ÿ": #"\ddot{y}"#,
>             
>             // Tilde
>             "ã": #"\tilde{a}"#, "ñ": #"\tilde{n}"#, "õ": #"\tilde{o}"#,
>             
>             // Special characters
>             "ç": #"\c{c}"#,
>             "ø": #"\o"#,
>             "å": #"\aa"#,
>             "æ": #"\ae"#,
>             "œ": #"\oe"#,
>             "ß": #"\ss"#,
>             "'": #"\\textquotesingle"#, <----------- HERE
>             
>             // Upper case variants
>             "Á": #"\acute{A}"#, "É": #"\acute{E}"#, "Í": #"\acute{I}"#,
>             "Ó": #"\acute{O}"#, "Ú": #"\acute{U}"#, "Ý": #"\acute{Y}"#,
>             "À": #"\grave{A}"#, "È": #"\grave{E}"#, "Ì": #"\grave{I}"#,
>             "Ò": #"\grave{O}"#, "Ù": #"\grave{U}"#,
>             "Â": #"\hat{A}"#, "Ê": #"\hat{E}"#, "Î": #"\hat{I}"#,
>             "Ô": #"\hat{O}"#, "Û": #"\hat{U}"#,
>             "Ä": #"\ddot{A}"#, "Ë": #"\ddot{E}"#, "Ï": #"\ddot{I}"#,
>             "Ö": #"\ddot{O}"#, "Ü": #"\ddot{U}"#,
>             "Ã": #"\tilde{A}"#, "Ñ": #"\tilde{N}"#, "Õ": #"\tilde{O}"#,
>             "Ç": #"\c{C}"#,
>             "Ø": #"\O"#,
>             "Å": #"\AA"#,
>             "Æ": #"\AE"#,
>             "Œ": #"\OE"#
>         ]
>         
>         return self.map { mappings[$0] ?? String($0) }.joined()
>     }
> }
> ```

Single quote is supported via the \upquote command.
