### ISSUE TITLE
sizeToFit Can't get frame

### ISSUE THREAD

**Issue by bingolib** [mgriebling/SwiftMath#36]
iosMath is ok，SwiftMath Can't get frame

**Comment by bingolib** [comment]
<img width="358" alt="image" src="https://github.com/user-attachments/assets/438f3225-bf4e-4f97-ac3e-35d151711d10">

**Comment by mgriebling** [comment]
If you're on a Mac try:  label.fittingSize()
otherwise use:  label.intrinsicContentSize()

@bingolib
