### ISSUE TITLE
No difference between 'display' and 'text'

### ISSUE THREAD

**Issue by DashingDave** [mgriebling/SwiftMath#5]
You might want to remove the "math mode" section of the Read Me's Advanced Config section. As far as I can tell, there isn't any difference between MTMathUILabelMode.display and MTMathUILabelMode.text. There wasn't in the iOSMath version of this, either, so it's the original authors' code that doesn't work as intended, not yours.

Users who see it will expect the code to properly format inline (text) mode, which the code can't, for some reason.

**Comment by mgriebling** [comment]
There is a small difference between the `.text` and `.label` modes in that the `.label` mode shows the equation(s) in a larger font than the text mode.  For now, I'll leave the documentation as is.

**Comment by swiftly-viper** [comment]
Based on this discussion, I gather that mixing regular text with inline equation text in SwiftMath is impossible. Would it be possible to confirm this @mgriebling?

Additionally, if I were to look into adding support for such a functionality, any advice on where I should look in the codebase? Thank you.
