### ISSUE TITLE
Crash!!! can you please check logs and fix it

### ISSUE THREAD

**Issue by ahsan-netshine** [mgriebling/SwiftMath#6]
<img width="1177" alt="Screenshot 2023-08-31 at 5 17 06 PM" src="https://github.com/mgriebling/SwiftMath/assets/133353631/316e1ce4-9563-4190-94fc-7b5f5089608a">
[stacktrace.txt](https://github.com/mgriebling/SwiftMath/files/12485974/stacktrace.txt)

**Comment by mgriebling** [comment]
Sorry, the crash report doesn't have enough information.
What is the LaTeX math command you were running when the error occurred?

**Comment by ahsan-netshine** [comment]
Actually I don't have access to latex, I have used it in one of my Apps, Can't we do anything to avoid this crash ?

**Comment by mgriebling** [comment]
I can't fix the problem if I can't duplicate the crash on my end.  So, I need to know what information your App is passing to the SwiftMath library when it crashes.

**Comment by mgriebling** [comment]
Unable to duplicate.  Insufficient information.
