### ISSUE TITLE
MTFontManager manager is nil

### ISSUE THREAD

**Issue by petersktang** [mgriebling/SwiftMath#7]
manager is accessible to external apps, fontManager is inaccessible, the below fixes manager nil issue.

<code>
public class MTFontManager {
    
    static public private(set) var manager: MTFontManager = {
        MTFontManager()
    }()
    
    let kDefaultFontSize = CGFloat(20)
    
    static var fontManager : MTFontManager {
        return manager
    }
</code>

**Comment by petersktang** [comment]
Included the above in pull request

**Comment by mgriebling** [comment]
Pull merged.
