### ISSUE TITLE
Line breaks not supported

### ISSUE THREAD

**Issue by Lu-TheCoder** [mgriebling/SwiftMath#9]
Greetings

I'm working on a math app and SwiftMath has been very useful in my project and I Love it..

However, whenever I stumble upon an edge case where I'm dealing with long equations that simply can't fit into one line,
I can't seem to find a solution to create either manual line breaks or automatic line breaks within Latex in case of the text being longer than the screens width.

Will there ever be support for this feature in future?

**Comment by mgriebling** [comment]
You can manually force line breaks using math mode commands (e.g., \\\\ as in \text{Quadratic roots: }x = \\\\ \frac{-b \pm \sqrt{b^2-4ac}}{2a} to give

<img width="318" alt="Screenshot 2023-02-23 at 8 00 59 AM" src="https://user-images.githubusercontent.com/2421348/220913664-bec1c330-51e1-4067-8fd3-37aa306ddd6f.png">

**Comment by Lu-TheCoder** [comment]
How do enable math mode?

Here's a screenshot of my MathView configuration

<img width="644" alt="Screenshot 2023-09-12 at 14 23 09" src="https://github.com/mgriebling/SwiftMath/assets/90724319/27521f1d-7605-42e8-a52a-6ed3b0b9c5e6">

Here's a screenshot of the Quadratic roots sample you provided used in my API

<img width="887" alt="Screenshot 2023-09-12 at 14 23 46" src="https://github.com/mgriebling/SwiftMath/assets/90724319/ac02933e-7211-4228-9804-7ea700cdfb33">


However the result does not create a new line as illustrated by your example.. 

<img width="371" alt="Screenshot 2023-09-12 at 14 24 05" src="https://github.com/mgriebling/SwiftMath/assets/90724319/b5a37ec5-d190-40b2-8d3b-40c770d6abaa">

Unless I am missing something or doing something incorrectly...

**Comment by Lu-TheCoder** [comment]
I managed to figure it out... instead of double slashes `\\` which only creates a space in between for whatever reason 
we need to use 4 slashes `\\\\` to get a new line break.

Here's a gif of it in action:

![new line break](https://github.com/mgriebling/SwiftMath/assets/90724319/f07e42ae-626e-4bf0-93fb-a043f9d747d8)

**Comment by mgriebling** [comment]
Math mode is always on.  There's nothing to enable.

When in quotes, backslashes "\" must be escaped so the "\\" should be "\\\\".
That's why all the commands appear to have double backslashes (in reality they're all being "escaped").
